package models

type TestBenchTable struct {
	HuGen     string
	HuVersion string
}

type Details struct {
	Vin       string `json:"vin"`
	Region    string `json:"region"`
	HUGen     string `json:"Gen"`
	HUVersion string `json:"version"`
	HuRelease string `json:"release"`

	Stage     string `json:"stage"`
	Cubicle   string `json:"Cubicle"`
	SwVersion string `json:"SwVersion"`
	Connected bool   `json:"connected"`
}
type GenDetails struct {
	HUGen     string `json:"Gen"`
	Vin       string `json:"vin"`
	HUVersion string `json:"version"`
	SwVersion string `json:"swversion"`
}

// type AutoGenerated struct {
// 	Gen20X struct {
// 		Version   []string  `json:"version"`
// 		SwVersion []float64 `json:"swVersion"`
// 	} `json:"Gen20x"`
// 	NTG struct {
// 		Version   []string  `json:"version"`
// 		SwVersion []float64 `json:"swVersion"`
// 	} `json:"NTG"`
// }
