package models

type TestBenchTable struct {
<<<<<<< HEAD
	HuVersion string `json:"huVersion"`
	HuGen     string `json:"huGen"`
}

type Gen20x struct {
	Version   []string  `json:"version"`
	SwVersion []float64 `json:"swVersion"`
}

type NTG struct {
	Version   []string  `json:"version"`
	SwVersion []float64 `json:"swVersion"`
}

type HU struct {
	Gen20x *Gen20x `json:"gen20x"`
	NTG    *NTG    `json:"ntg"`
=======
	HuGen     string
	HuVersion string
>>>>>>> 7f412a99682e317ed3e724c16ba53c62ced9f068
}

type Details struct {
	Vin       string `json:"vin"`
	Region    string `json:"region"`
	HUGen     string `json:"Gen"`
	HUVersion string `json:"version"`
	HuRelease string `json:"release"`

	Stage     string `json:"stage"`
	Cubicle   string `json:"Cubicle"`
	SwVersion string `json:"SwVersion"`
	Connected bool   `json:"connected"`
}
type GenDetails struct {
	HUGen     string `json:"Gen"`
	Vin       string `json:"vin"`
	HUVersion string `json:"version"`
	SwVersion string `json:"swversion"`
}

// type AutoGenerated struct {
// 	Gen20X struct {
// 		Version   []string  `json:"version"`
// 		SwVersion []float64 `json:"swVersion"`
// 	} `json:"Gen20x"`
// 	NTG struct {
// 		Version   []string  `json:"version"`
// 		SwVersion []float64 `json:"swVersion"`
// 	} `json:"NTG"`
// }
